### ISSUE TITLE
The migrations url is here

### ISSUE THREAD

**Issue by christhomas** [yakotta/luxemanagers#25]
https://github.com/yakotta/luxemanagers/blob/a32b2181e2e53831b94a09235005d795204e1fa0/index.php#L61

**Comment by yakotta** [comment]
I tried that too and it's still not working

<img width="1440" alt="screen shot 2018-07-08 at 10 33 42 am" src="https://user-images.githubusercontent.com/16373396/42422427-6d191634-829a-11e8-8c07-4d5cddd3b15c.png">
